name: Build app
run-name: build and publish

on:
  push:
    tags:
      - "v*"
  
jobs:
  prod-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build env
        run: |
          sudo apt update
          sudo apt install openjdk-21-jdk -y
          sudo apt install gradle -y      

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" 

          gh release upload "$tag" \
              build/libs/*